@startuml
start
!pragma useVerticalIf on
skinparam linetype ortho
skinparam shadowing false

title Access Control At The Door

partition "Facility User" {
  :Arrive at controlled door;
}

partition " Default AMS" {
  :Receive credential + door ID;
  :Lookup permit policy store (DB Lookup);
  :Evaluate standard access rules;

}

if (Standard access allowed?) then (Yes)
  :Log ALLOW;
  :Intitiate defined access protocol ;
  stop
else (No)
  :Log DENY ( Reason: standard);
  :Access denied displayed;
  partition "AMS Emergency Protocols"{
  if (Emergency declared?) then (Yes)
    :Capture justification + incident ID;

    if (Valid incident ID?) then (Yes)
      :Record justification;
      :Create emergency AccessGrant \n for user using incident ID;

      if (Room allows emergency access?) then (No)
        :Log DENY (hard constraint);
        stop
      else (Yes)
        :Log ALLOW (emergency);
        : Intitiate emergency access protocol;
        stop
      endif


    else (No)
      :Log DENY (Reason: Invalid incident ID);
      :Entry denied;
      stop
    endif

  else (No)
    stop
  endif
  }
endif

@enduml