@startuml
start
!pragma useVerticalIf on
skinparam linetype ortho
skinparam shadowing false

title Access Control At The Door

partition "Facility User" {
  :Arrive at controlled door;
}

partition " Default AMS" {
  :Receive credential + door ID;
  :Lookup permit policy store (DB Lookup);
  :Evaluate standard access rules;

}

if (Standard access allowed?) then (Yes)
  :Log ALLOW;
  :Intitiate defined access protocol \n (standard entry, supervisor necessary etc)) ;
  stop
else (No)
  :Log DENY ( Reason: standard);
  :Access denied displayed;
  partition "Emergency Access Control System"{
  if (Emergency declared?) then (Yes)
    :Capture justification + incident ID;

    if (Valid incident ID?) then (Yes)
      :Record justification;
      :Create temporary emergency grant;
      :Re-check hard constraints;

      if (Hard constraint blocks entry?) then (Yes)
        :Log DENY (hard constraint);
        :Entry denied;
        stop
      else (No)
        :Log ALLOW (emergency);
        :Unlock door (time-limited);
        :Enter zone;
        stop
      endif


    else (No)
      :Log DENY (Reason: Invalid incident ID);
      :Entry denied;
      stop
    endif

  else (No)
    stop
  endif
  }
endif

@enduml