@startuml

skinparam actorStyle awesome

' Privileged authorities (break-glass / override / suspend)
actor "Privilege Broker" as PrivAuthority


' General facility population (can request emergency access)
actor "Facility User (Researcher, Technician etc.)" as FacilityUser



' Audit stakeholders
actor "Audit Stakeholder" as AuditStakeholder
PrivAuthority -|> AuditStakeholder
actor "Auditor / Compliance" as Auditor
Auditor -|> AuditStakeholder

rectangle "Emergency Access System" {

  usecase "Request Emergency Access" as UC_RequestEA
  usecase "Grant Emergency Access\n(Break-glass)" as UC_GrantEA
  usecase "Manual Override Door/Zone" as UC_Override
  usecase "Suspend/Cancel Permit/Access" as UC_Suspend
  usecase "Record Justification &\nIncident Reference" as UC_Justify
  usecase "Post-incident Review / Audit" as UC_Audit
}

'Associations'
FacilityUser     --> UC_RequestEA
PrivAuthority    --> UC_GrantEA
PrivAuthority    --> UC_Override
PrivAuthority    --> UC_Suspend
AuditStakeholder --> UC_Audit


UC_GrantEA  ..> UC_Justify : <<include>>
UC_Override ..> UC_Justify : <<include>>
UC_Suspend  ..> UC_Justify : <<include>>


UC_Audit ..> UC_GrantEA  : <<extend>>
UC_Audit ..> UC_Override : <<extend>>
UC_Audit ..> UC_Suspend  : <<extend>>

@enduml